name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  syncfusion_flutter_gauges: ^29.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/first.jpeg
    - assets/first1.jpeg
    - assets/onboard.jpeg
    - assets/new.jpg
    - assets/height.jpg
    - assets/images2.jpeg
    - assets/fit1.jpg
    - assets/fit2.jpg

